const sampleListings = [
  {
    title: "Cozy Mountain Cabin",
    description: "A peaceful retreat surrounded by scenic mountain views.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 120,
    location: "Aspen",
    country: "USA",
  },
  {
    title: "Modern City Apartment",
    description: "An urban apartment with sleek interiors and a skyline view.",
    image: "https://images.unsplash.com/photo-1586105251261-72a756497a12",
    price: 200,
    location: "New York",
    country: "USA",
  },
  {
    title: "Beachside Bungalow",
    description:
      "Step out of the door and right onto the sand in this beachside home.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 150,
    location: "Malibu",
    country: "USA",
  },
  {
    title: "Countryside Villa",
    description: "A luxurious villa surrounded by vineyards and hills.",
    image: "https://images.unsplash.com/photo-1560185127-6a8c6bfb07c1",
    price: 180,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Tokyo Studio",
    description:
      "Compact and functional studio space in the heart of the city.",
    image: "https://images.unsplash.com/photo-1578898884081-c65b73d152d9",
    price: 90,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Lakefront Cottage",
    description:
      "Quiet cottage right on the lake with breathtaking sunset views.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 140,
    location: "Lake Tahoe",
    country: "USA",
  },
  {
    title: "Rustic Barn Stay",
    description: "Converted barn with cozy charm and modern amenities.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    price: 100,
    location: "Nashville",
    country: "USA",
  },
  {
    title: "Historic Stone House",
    description: "Old-world charm in this beautifully preserved stone house.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    price: 160,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Desert Dome Home",
    description: "Unique dome house in the heart of the desert.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 130,
    location: "Joshua Tree",
    country: "USA",
  },
  {
    title: "Alpine Chalet",
    description: "Perfect for ski season or summer hiking adventures.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 170,
    location: "Zermatt",
    country: "Switzerland",
  },

  {
    title: "Lakeside Mountain Cabin",
    description: "Charming cabin with both lake and mountain views.",
    image: "https://images.unsplash.com/photo-1605276374977-27d5bba9f6f4",
    price: 125,
    location: "Lake Placid",
    country: "USA",
  },
  {
    title: "Urban Loft Apartment",
    description: "A spacious loft in a trendy downtown neighborhood.",
    image: "https://images.unsplash.com/photo-1599423300746-b62533397364",
    price: 210,
    location: "Chicago",
    country: "USA",
  },
  {
    title: "Tropical Beach Bungalow",
    description: "A private bungalow steps from the crystal clear sea.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 155,
    location: "Maui",
    country: "USA",
  },
  {
    title: "Spanish Vineyard Villa",
    description: "Traditional villa set among rolling Spanish vineyards.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 190,
    location: "La Rioja",
    country: "Spain",
  },
  {
    title: "Minimalist Tokyo Apartment",
    description: "A clean and minimalist apartment in central Tokyo.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    price: 95,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Lakeside Log Cabin",
    description: "Log cabin ideal for fishing and fireside evenings.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 135,
    location: "Big Bear Lake",
    country: "USA",
  },
  {
    title: "Vintage Farmhouse",
    description: "A restored farmhouse with vintage decor.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    price: 105,
    location: "Vermont",
    country: "USA",
  },
  {
    title: "Classic English Cottage",
    description: "Traditional stone cottage in the English countryside.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 165,
    location: "Cotswolds",
    country: "UK",
  },
  {
    title: "Desert Adobe House",
    description: "Cool and earthy adobe-style house in the desert.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 135,
    location: "Sedona",
    country: "USA",
  },
  {
    title: "Luxury Mountain Chalet",
    description: "Modern alpine retreat with luxury finishes.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 175,
    location: "Banff",
    country: "Canada",
  },

  {
    title: "Cabin by the River",
    description: "Relax to the sound of the river at this hidden cabin.",
    image: "https://images.unsplash.com/photo-1599423300746-b62533397364",
    price: 115,
    location: "Smoky Mountains",
    country: "USA",
  },
  {
    title: "High-Rise Penthouse",
    description: "Enjoy sweeping views from the top floor of this high-rise.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 250,
    location: "Seattle",
    country: "USA",
  },
  {
    title: "Surf Shack",
    description: "Rustic beach shack perfect for surf lovers.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 145,
    location: "Santa Cruz",
    country: "USA",
  },
  {
    title: "Mediterranean Hilltop Villa",
    description: "Hilltop villa with a panoramic view of the Mediterranean.",
    image: "https://images.unsplash.com/photo-1560185127-6a8c6bfb07c1",
    price: 185,
    location: "Nice",
    country: "France",
  },
  {
    title: "Quiet Tokyo Flat",
    description: "A tranquil flat tucked away from the bustle of the city.",
    image: "https://images.unsplash.com/photo-1578898884081-c65b73d152d9",
    price: 88,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Mountain View Cabin",
    description: "Wake up to stunning mountain views every morning.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 145,
    location: "Blue Ridge",
    country: "USA",
  },
  {
    title: "Country Ranch",
    description: "Spacious ranch home with horses and open skies.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    price: 110,
    location: "Texas Hill Country",
    country: "USA",
  },
  {
    title: "Scottish Castle Stay",
    description: "Live like royalty in this historic castle estate.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    price: 300,
    location: "Inverness",
    country: "Scotland",
  },
  {
    title: "Off-Grid Desert Retreat",
    description: "Disconnect and unwind in a fully off-grid desert home.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 125,
    location: "Moab",
    country: "USA",
  },
  {
    title: "Swiss Alps Lodge",
    description: "Experience the magic of the Alps from this cozy lodge.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 180,
    location: "Interlaken",
    country: "Switzerland",
  },
];

module.exports = {
  data: sampleListings,
};
